name: CSSS
author: Martin Gingras
markdown: redcarpet
url: csss.herokuapp.com
port: 5050
safe: true
pygments: true
future: false
exclude:
- README.md
- Gemfile
- Gemfile.lock
- Procfile
- vendor
- gems
- Rakefile