name: CSSS
author: Abe Fehr
markdown: redcarpet
permalink: /:categories/:title
url: csss.herokuapp.com
port: 5050
safe: true
pygments: true
future: false
threeArray: [3,6,9,12, 15, 18, 21]
fourArray: [4,8,12,16,20,24,28,32]
exclude:
- README.md
- Gemfile
- Gemfile.lock
- Procfile
- vendor
- gems
- Rakefile
